#!/usr/bin/env bash
# install_token_refresh_timer.sh
#
# Installs a systemd timer on the GCP runtime VM that refreshes the Kite access
# token every morning at 08:30 IST (03:00 UTC) before market opens at 09:15 IST.
#
# Run this ONCE on the VM after first deploy:
#   gcloud compute ssh option-trading-runtime-01 --zone=asia-south1-b \
#     --project=algo-trading-496203 \
#     --command "cd /opt/option_trading && sudo bash ops/gcp/install_token_refresh_timer.sh"
#
# Prerequisites:
#   The following env vars must be set in /opt/option_trading/.env.totp on the VM.
#   This file is NOT committed — create it manually or push via publish_runtime_config.sh.
#
#   KITE_USER_ID       Zerodha login ID (e.g. BV2032)
#   KITE_PASSWORD      Zerodha login password
#   KITE_TOTP_SECRET   32-char base32 secret from Zerodha authenticator setup
#   KITE_API_KEY       Kite Connect app API key
#   KITE_API_SECRET    Kite Connect app API secret
#
# How to get KITE_TOTP_SECRET:
#   Zerodha app → Settings → Security → External TOTP app → Setup
#   On the QR/setup screen, choose "Can't scan?" or "Show secret" → copy the 32-char code.
#   Store it in /opt/option_trading/.env.totp on the VM (chmod 600).

set -euo pipefail

REPO_ROOT="/opt/option_trading"
ENV_TOTP="${REPO_ROOT}/.env.totp"
PY_BIN="${REPO_ROOT}/.venv/bin/python"
LOG_FILE="/var/log/kite-token-refresh.log"
SERVICE_NAME="kite-token-refresh"

# ── Guard: must be run as root (for systemd unit install) ────────────────────
if [[ "$(id -u)" != "0" ]]; then
  echo "Error: run as root (sudo)" >&2
  exit 1
fi

# ── Guard: .env.totp must exist ──────────────────────────────────────────────
if [[ ! -f "${ENV_TOTP}" ]]; then
  echo ""
  echo "ERROR: ${ENV_TOTP} not found."
  echo ""
  echo "Create it with:"
  echo "  sudo tee ${ENV_TOTP} <<'EOF'"
  echo "  KITE_USER_ID=BV2032"
  echo "  KITE_PASSWORD=<your zerodha password>"
  echo "  KITE_TOTP_SECRET=<32-char base32 secret>"
  echo "  KITE_API_KEY=<api key>"
  echo "  KITE_API_SECRET=<api secret>"
  echo "  EOF"
  echo "  sudo chmod 600 ${ENV_TOTP}"
  echo ""
  exit 1
fi
chmod 600 "${ENV_TOTP}"

# ── Create the refresh script ────────────────────────────────────────────────
REFRESH_SCRIPT="/usr/local/bin/kite-token-refresh.sh"
cat > "${REFRESH_SCRIPT}" <<SCRIPT
#!/usr/bin/env bash
# Auto-generated by install_token_refresh_timer.sh — do not edit manually.
set -euo pipefail

REPO_ROOT="${REPO_ROOT}"
LOG_FILE="${LOG_FILE}"
ENV_TOTP="${ENV_TOTP}"
PY_BIN="${PY_BIN}"

echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] Kite token refresh starting" | tee -a "\${LOG_FILE}"

# Load TOTP secrets
set -a
source "\${ENV_TOTP}"
set +a

# Run headless TOTP auth
if "\${PY_BIN}" -m ingestion_app.kite_totp_auth \
  --credentials-path "\${REPO_ROOT}/ingestion_app/credentials.json"; then

  echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] Token refresh OK — restarting ingestion_app" | tee -a "\${LOG_FILE}"

  # Force-recreate so Docker picks up the updated credentials.json bind-mount
  cd "\${REPO_ROOT}"
  docker compose up -d --no-deps --force-recreate ingestion_app 2>&1 | tee -a "\${LOG_FILE}"

  # Optionally push fresh credentials to GCS runtime-config bucket so other
  # consumers (depth_collector on live profile) also get the new token.
  if [[ -f "ops/gcp/publish_runtime_config.sh" ]] && command -v gcloud &>/dev/null; then
    echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] Pushing updated credentials to GCS" | tee -a "\${LOG_FILE}"
    bash ops/gcp/publish_runtime_config.sh 2>&1 | tee -a "\${LOG_FILE}" || true
  fi

  echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] Token refresh complete" | tee -a "\${LOG_FILE}"
else
  echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] ERROR: Token refresh FAILED — ingestion_app not restarted" | tee -a "\${LOG_FILE}"
  exit 1
fi
SCRIPT
chmod +x "${REFRESH_SCRIPT}"
echo "Refresh script written to ${REFRESH_SCRIPT}"

# ── systemd service ──────────────────────────────────────────────────────────
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<UNIT
[Unit]
Description=Kite Connect daily token refresh
After=network-online.target docker.service
Wants=network-online.target
StartLimitIntervalSec=300
StartLimitBurst=2

[Service]
Type=oneshot
ExecStart=${REFRESH_SCRIPT}
StandardOutput=journal
StandardError=journal
# Retry once on failure (e.g. transient network issue at startup)
Restart=on-failure
RestartSec=120
UNIT

# ── systemd timer (08:30 IST = 03:00 UTC) ───────────────────────────────────
cat > "/etc/systemd/system/${SERVICE_NAME}.timer" <<UNIT
[Unit]
Description=Run Kite token refresh daily at 08:30 IST (03:00 UTC)

[Timer]
# 03:00 UTC = 08:30 IST
OnCalendar=*-*-* 03:00:00 UTC
# If the VM was off at 03:00, run as soon as it boots (within 5 min window)
Persistent=true
RandomizedDelaySec=60

[Install]
WantedBy=timers.target
UNIT

# ── Enable and start ─────────────────────────────────────────────────────────
systemctl daemon-reload
systemctl enable --now "${SERVICE_NAME}.timer"

echo ""
echo "Timer installed and enabled."
echo ""
systemctl status "${SERVICE_NAME}.timer" --no-pager
echo ""
echo "Next scheduled run:"
systemctl list-timers "${SERVICE_NAME}.timer" --no-pager
echo ""
echo "To run immediately (test):"
echo "  sudo systemctl start ${SERVICE_NAME}.service"
echo "  sudo journalctl -u ${SERVICE_NAME}.service -f"
echo ""
echo "Logs: ${LOG_FILE}"
