import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, Optional

import joblib

from .pipeline_layout import ensure_layout_dirs, resolve_market_archive_base, resolve_vix_source, training_workspace
from .train_two_year_pipeline import (
    LABEL_TARGET_BASE,
    LABEL_TARGET_PATH_TP_SL,
    LABEL_TARGET_PATH_TP_SL_TIME_STOP_ZERO,
    PreprocessConfig,
    TradingObjectiveConfig,
    run_two_year_pipeline,
)


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _run_id() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def _safe_name(value: str) -> str:
    return "".join(ch if (ch.isalnum() or ch in ("_", "-", ".")) else "_" for ch in str(value))


def _to_rel_repo(path: Path) -> str:
    root = Path.cwd().resolve()
    resolved = path.resolve()
    try:
        return str(resolved.relative_to(root)).replace("\\", "/")
    except Exception:
        return str(path).replace("\\", "/")


def _read_json(path: Path) -> Dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _build_threshold_report(training_report: Dict[str, object]) -> Dict[str, object]:
    utility_cfg = training_report.get("trading_utility_config") or {}
    cv_cfg = training_report.get("cv_config") or {}
    preprocessing = training_report.get("preprocessing") or {}
    return {
        "created_at_utc": _utc_now(),
        "rows_total": training_report.get("rows_total"),
        "days_total": training_report.get("days_total"),
        "feature_profile": training_report.get("feature_profile"),
        "objective": training_report.get("objective"),
        "label_target": training_report.get("label_target"),
        "cv_config": cv_cfg,
        "preprocessing": preprocessing,
        "trading_utility_config": utility_cfg,
        "best_experiment": training_report.get("best_experiment"),
        "leaderboard_top": (training_report.get("leaderboard") or [])[:5],
    }


def _extract_required_features(*, model_package_path: Path, training_report: Dict[str, object]) -> list[str]:
    model_pkg = joblib.load(model_package_path)
    if isinstance(model_pkg, dict):
        cols = model_pkg.get("feature_columns")
        if isinstance(cols, list) and cols:
            return [str(c) for c in cols]
    best = training_report.get("best_experiment") or {}
    cols = best.get("feature_columns") if isinstance(best, dict) else None
    if isinstance(cols, list) and cols:
        return [str(c) for c in cols]
    raise ValueError("could not determine required feature columns from model package or training report")


def _cleanup_workspace(path: Path) -> None:
    if path.exists() and path.is_dir():
        shutil.rmtree(path, ignore_errors=True)


def _register_catalog_entry(
    *,
    catalog_id: str,
    instance_key: str,
    model_group: str,
    profile_id: str,
    model_package: Path,
    threshold_report: Path,
    training_report: Path,
) -> Path:
    catalog_dir = Path("ml_pipeline/model_catalog/models") / str(catalog_id)
    catalog_dir.mkdir(parents=True, exist_ok=True)
    title = f"{model_group} | {profile_id}"
    payload = {
        "instance_key": instance_key,
        "profile_key": profile_id,
        "title": title,
        "summary": f"Auto-generated catalog entry for {title}",
        "description": "Generated by train_model_standard.",
        "recommended": False,
        "model_package": _to_rel_repo(model_package),
        "threshold_report": _to_rel_repo(threshold_report),
        "training_report_path": _to_rel_repo(training_report),
    }
    out_path = catalog_dir / "model.json"
    _write_json(out_path, payload)
    return out_path


def run_cli(argv: Optional[Iterable[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Standardized model trainer: train + publish into by_features model-group/profile layout."
    )
    parser.add_argument("--model-group", required=True, help="e.g. core_v2/h5_ts0")
    parser.add_argument("--profile-id", required=True, help="e.g. thr56")
    parser.add_argument("--feature-profile", default=None, help="Defaults to model-group first segment")
    parser.add_argument("--base-path", default=None, help="Archive base path")
    parser.add_argument("--lookback-years", type=int, default=2)
    parser.add_argument("--end-day", default=None)
    parser.add_argument("--reserve-months", type=int, default=3)
    parser.add_argument("--vix-path", default=None)
    parser.add_argument("--chunk-size-days", type=int, default=70)
    parser.add_argument(
        "--objective",
        default="trade_utility",
        choices=["rmse", "brier", "f1", "roc_auc", "pr_auc", "accuracy", "precision", "recall", "trade_utility"],
    )
    parser.add_argument(
        "--label-target",
        default=LABEL_TARGET_PATH_TP_SL,
        choices=[LABEL_TARGET_PATH_TP_SL, LABEL_TARGET_BASE, LABEL_TARGET_PATH_TP_SL_TIME_STOP_ZERO],
    )
    parser.add_argument("--label-horizon-minutes", type=int, default=15)
    parser.add_argument("--label-stop-loss-pct", type=float, default=0.20)
    parser.add_argument("--label-take-profit-pct", type=float, default=0.30)
    parser.add_argument("--train-days", type=int, default=180)
    parser.add_argument("--valid-days", type=int, default=30)
    parser.add_argument("--test-days", type=int, default=30)
    parser.add_argument("--step-days", type=int, default=30)
    parser.add_argument("--purge-days", type=int, default=0)
    parser.add_argument("--embargo-days", type=int, default=0)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--max-experiments", type=int, default=18)
    parser.add_argument("--max-missing-rate", type=float, default=0.35)
    parser.add_argument("--clip-lower-q", type=float, default=0.01)
    parser.add_argument("--clip-upper-q", type=float, default=0.99)
    parser.add_argument("--utility-ce-threshold", type=float, default=0.60)
    parser.add_argument("--utility-pe-threshold", type=float, default=0.60)
    parser.add_argument("--utility-cost-per-trade", type=float, default=0.0006)
    parser.add_argument("--utility-min-profit-factor", type=float, default=1.30)
    parser.add_argument("--utility-max-equity-drawdown-pct", type=float, default=0.15)
    parser.add_argument("--utility-min-trades", type=int, default=50)
    parser.add_argument("--utility-risk-per-trade-pct", type=float, default=0.01)
    parser.add_argument("--utility-discard-time-stop", action="store_true")
    parser.add_argument("--catalog-id", default=None, help="If set, writes/updates ml_pipeline/model_catalog/models/<id>/model.json")
    parser.add_argument("--instance-key", default=None, help="Catalog instance key (defaults to model_group + profile)")
    parser.add_argument("--keep-temp-artifacts", action="store_true", help="Keep intermediate prefix artifacts from run_two_year_pipeline")
    args = parser.parse_args(list(argv) if argv is not None else None)

    feature_profile = str(args.feature_profile) if args.feature_profile else str(args.model_group).split("/", 1)[0]
    ensure_layout_dirs()
    base = resolve_market_archive_base(explicit_base=args.base_path)
    if base is None:
        print("ERROR: archive base path not found")
        return 2
    vix_source = resolve_vix_source(explicit_vix=args.vix_path)

    run_id = _run_id()
    artifact_prefix = f"tmp_{_safe_name(args.model_group)}_{_safe_name(args.profile_id)}_{run_id}"
    run_workspace = training_workspace(run_id=run_id)
    summary = run_two_year_pipeline(
        base_path=base,
        lookback_years=int(args.lookback_years),
        end_day=args.end_day,
        reserve_months=int(args.reserve_months),
        vix_path=vix_source,
        chunk_size_days=int(args.chunk_size_days),
        artifact_prefix=artifact_prefix,
        objective=str(args.objective),
        feature_profile=feature_profile,
        label_target=str(args.label_target),
        label_horizon_minutes=int(args.label_horizon_minutes),
        label_stop_loss_pct=float(args.label_stop_loss_pct),
        label_take_profit_pct=float(args.label_take_profit_pct),
        train_days=int(args.train_days),
        valid_days=int(args.valid_days),
        test_days=int(args.test_days),
        step_days=int(args.step_days),
        purge_days=int(args.purge_days),
        embargo_days=int(args.embargo_days),
        random_state=int(args.random_state),
        max_experiments=(int(args.max_experiments) if args.max_experiments is not None else None),
        preprocess_cfg=PreprocessConfig(
            max_missing_rate=float(args.max_missing_rate),
            clip_lower_q=float(args.clip_lower_q),
            clip_upper_q=float(args.clip_upper_q),
        ),
        utility_cfg=TradingObjectiveConfig(
            ce_threshold=float(args.utility_ce_threshold),
            pe_threshold=float(args.utility_pe_threshold),
            cost_per_trade=float(args.utility_cost_per_trade),
            min_profit_factor=float(args.utility_min_profit_factor),
            max_equity_drawdown_pct=float(args.utility_max_equity_drawdown_pct),
            min_trades=int(args.utility_min_trades),
            take_profit_pct=float(args.label_take_profit_pct),
            stop_loss_pct=float(args.label_stop_loss_pct),
            discard_time_stop=bool(args.utility_discard_time_stop),
            risk_per_trade_pct=float(args.utility_risk_per_trade_pct),
        ),
        artifacts_root=run_workspace,
        reuse_artifacts=False,
    )

    by_features_root = Path("ml_pipeline/artifacts/models/by_features")
    group_root = by_features_root / str(args.model_group)
    model_out = group_root / "model" / "model.joblib"
    profile_root = group_root / "config" / "profiles" / str(args.profile_id)
    profile_training_out = profile_root / "training_report.json"
    profile_threshold_out = profile_root / "threshold_report.json"
    contract_out = group_root / "model_contract.json"
    reports_out = group_root / "reports" / "training"
    data_run_out = group_root / "data" / "training_runs" / run_id
    reports_out.mkdir(parents=True, exist_ok=True)
    data_run_out.mkdir(parents=True, exist_ok=True)

    src_artifacts = {k: Path(v) for k, v in dict(summary.get("artifacts") or {}).items()}
    required_keys = {"panel", "features", "labeled", "training_report", "model_package", "run_summary", "holdout_days"}
    missing = required_keys - set(src_artifacts.keys())
    if missing:
        raise RuntimeError(f"training summary missing expected artifacts: {sorted(missing)}")

    _copy(src_artifacts["model_package"], model_out)
    _copy(src_artifacts["training_report"], profile_training_out)
    training_report = _read_json(profile_training_out)
    threshold_report = _build_threshold_report(training_report)
    _write_json(profile_threshold_out, threshold_report)

    required_features = _extract_required_features(model_package_path=model_out, training_report=training_report)
    model_contract = {
        "schema_version": "1.0",
        "model_group": str(args.model_group),
        "source": "model_package.feature_columns",
        "required_features": required_features,
        "allow_extra_features": True,
        "missing_policy": "error",
    }
    _write_json(contract_out, model_contract)

    for key in ("panel", "features", "labeled", "run_summary", "holdout_days"):
        src = src_artifacts[key]
        _copy(src, data_run_out / src.name)

    publish_summary = {
        "created_at_utc": _utc_now(),
        "run_id": run_id,
        "model_group": str(args.model_group),
        "profile_id": str(args.profile_id),
        "feature_profile": feature_profile,
        "published_paths": {
            "model_package": _to_rel_repo(model_out),
            "training_report": _to_rel_repo(profile_training_out),
            "threshold_report": _to_rel_repo(profile_threshold_out),
            "model_contract": _to_rel_repo(contract_out),
            "data_run_dir": _to_rel_repo(data_run_out),
        },
    }
    _write_json(reports_out / f"run_{run_id}.json", publish_summary)
    _write_json(reports_out / "latest.json", publish_summary)

    catalog_path = None
    if args.catalog_id:
        default_instance = f"{str(args.model_group).replace('/', '_')}_{str(args.profile_id)}"
        catalog_path = _register_catalog_entry(
            catalog_id=str(args.catalog_id),
            instance_key=(str(args.instance_key) if args.instance_key else default_instance),
            model_group=str(args.model_group),
            profile_id=str(args.profile_id),
            model_package=model_out,
            threshold_report=profile_threshold_out,
            training_report=profile_training_out,
        )
        publish_summary["catalog_manifest"] = _to_rel_repo(catalog_path)
        _write_json(reports_out / f"run_{run_id}.json", publish_summary)
        _write_json(reports_out / "latest.json", publish_summary)

    if not bool(args.keep_temp_artifacts):
        _cleanup_workspace(run_workspace)

    print(json.dumps(publish_summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(run_cli())
