"""ENTRY fills must correlate strategy_positions by signal_id, not position_id
(found 2026-07-22 review).

ENTRY TradeSignals never carry position_id -- it's generated by
tracker.open_position() AFTER the TradeSignal (and its FillEvent) already
exist. The old guard `if status != "filled" or not position_id: return`
therefore returned early on EVERY entry fill: fill_entry_price and
slippage_entry_pct were never written for any live trade, and because
_get_entry_fill_price() looks up fill_entry_price by position_id, fill_pnl_pct
was never computed on exit either -- the entire fill-truth P&L/slippage
feature was dead for the whole live path.
"""
from __future__ import annotations

from execution_app.fill_tracker import FillTracker


class _FakeUpdateResult:
    def __init__(self, matched):
        self.matched_count = matched


class _FakePositionsColl:
    def __init__(self, docs=None):
        self.docs = docs or []
        self.updates: list[tuple[dict, dict]] = []

    def update_one(self, filt, update):
        self.updates.append((dict(filt), dict(update)))
        for d in self.docs:
            if all(d.get(k) == v for k, v in filt.items()):
                d.update(update.get("$set", {}))
                return _FakeUpdateResult(1)
        return _FakeUpdateResult(0)

    def find_one(self, filt, projection=None):
        for d in self.docs:
            if all(d.get(k) == v for k, v in filt.items()):
                return d
        return None


class _FakeFillsColl:
    def __init__(self):
        self.inserted = []

    def insert_one(self, doc):
        self.inserted.append(doc)


def _tracker(positions_coll):
    t = object.__new__(FillTracker)  # bypass __init__ (no real Redis/Mongo)
    t._fills_coll = _FakeFillsColl()
    t._positions_coll = positions_coll
    return t


def test_entry_fill_updates_position_by_signal_id():
    positions = _FakePositionsColl(docs=[{"signal_id": "sig-1", "position_id": "pos-1"}])
    tracker = _tracker(positions)
    tracker._handle_fill("1-1", {
        "signal_id": "sig-1", "signal_type": "ENTRY", "status": "filled",
        "fill_price": "102.5", "order_id": "o1", "filled_at": "t1", "slippage_pct": "0.01",
    })
    doc = positions.docs[0]
    assert doc["fill_entry_price"] == 102.5
    assert positions.updates[0][0] == {"signal_id": "sig-1"}


def test_entry_fill_without_signal_id_is_a_noop_not_a_crash():
    positions = _FakePositionsColl()
    tracker = _tracker(positions)
    tracker._handle_fill("1-1", {
        "signal_type": "ENTRY", "status": "filled", "fill_price": "102.5",
    })
    assert positions.updates == []


def test_exit_fill_computes_pnl_from_entry_fill_price_written_by_entry_correlation():
    """End-to-end: an entry fill (correlated by signal_id) must make its
    fill_entry_price visible to the later exit fill (correlated by
    position_id) so fill_pnl_pct actually computes -- this was silently
    None for every live trade before the fix."""
    positions = _FakePositionsColl(docs=[{"signal_id": "sig-1", "position_id": "pos-1"}])
    tracker = _tracker(positions)
    tracker._handle_fill("1-1", {
        "signal_id": "sig-1", "signal_type": "ENTRY", "status": "filled",
        "fill_price": "100.0", "order_id": "o1", "filled_at": "t1",
    })
    tracker._handle_fill("1-2", {
        "signal_id": "sig-2", "signal_type": "EXIT", "status": "filled",
        "position_id": "pos-1", "fill_price": "120.0", "order_id": "o2", "filled_at": "t2",
    })
    doc = positions.docs[0]
    assert doc["fill_entry_price"] == 100.0
    assert doc["fill_exit_price"] == 120.0
    assert doc["fill_pnl_pct"] == 0.2


def test_exit_fill_without_position_id_is_a_noop():
    positions = _FakePositionsColl()
    tracker = _tracker(positions)
    tracker._handle_fill("1-1", {
        "signal_type": "EXIT", "status": "filled", "fill_price": "120.0",
    })
    assert positions.updates == []


def test_non_filled_status_never_updates_positions():
    positions = _FakePositionsColl(docs=[{"signal_id": "sig-1"}])
    tracker = _tracker(positions)
    tracker._handle_fill("1-1", {
        "signal_id": "sig-1", "signal_type": "ENTRY", "status": "rejected",
    })
    assert positions.updates == []
