from __future__ import annotations

from typing import Dict, List

from ..contracts.types import FeatureSetSpec


DEFAULT_FEATURE_SET_SPECS: List[FeatureSetSpec] = [
    FeatureSetSpec(name="fo_full"),
    FeatureSetSpec(
        name="f5_core_atr",
        include_regex=(
            r"^f5_ret_",
            r"^f5_ema_",
            r"^f5_rsi_",
            r"^f5_atr_",
            r"^f5_bar_range_",
            r"^f5_vwap_distance$",
            r"^f5_dist_from_day_",
            r"^f5_basis",
            r"^f5_oi_",
            r"^f5_volume_",
            r"^f5_pcr_oi$",
            r"^f5_ce_pe_",
            r"^f5_bar_index$",
            r"^f5_minute_of_day$",
            r"^f5_day_of_week$",
            r"^f5_opening_range_",
        ),
    ),
    FeatureSetSpec(name="fo_no_opening_range", exclude_regex=(r"^opening_range_", r"^ctx_opening_range_")),
    FeatureSetSpec(
        name="fo_no_time_context",
        exclude_regex=(
            r"^minute_of_day$",
            r"^day_of_week$",
            r"^minute_index$",
            r"^time_minute_of_day$",
            r"^time_day_of_week$",
            r"^time_minute_index$",
        ),
    ),
    FeatureSetSpec(
        name="fo_no_oi_volume",
        exclude_regex=(
            r"^ce_oi_total$",
            r"^pe_oi_total$",
            r"^ce_volume_total$",
            r"^pe_volume_total$",
            r"^pcr_oi$",
            r"^ce_pe_oi_diff$",
            r"^ce_pe_volume_diff$",
            r"^atm_oi_change_1m$",
            r"^opt_.*_oi$",
            r"^opt_.*_volume$",
            r"^fut_flow_volume$",
            r"^fut_flow_oi$",
            r"^fut_flow_rel_volume_20$",
            r"^fut_flow_volume_accel_1m$",
            r"^fut_flow_oi_change_1m$",
            r"^fut_flow_oi_change_5m$",
            r"^fut_flow_oi_rel_20$",
            r"^fut_flow_oi_zscore_20$",
            r"^opt_flow_ce_oi_total$",
            r"^opt_flow_pe_oi_total$",
            r"^opt_flow_ce_volume_total$",
            r"^opt_flow_pe_volume_total$",
            r"^opt_flow_pcr_oi$",
            r"^opt_flow_atm_oi_change_1m$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_volume_diff$",
            r"^opt_flow_options_volume_total$",
            r"^opt_flow_rel_volume_20$",
        ),
    ),
    FeatureSetSpec(name="fo_no_otm_levels", exclude_regex=(r"^strike_m1$", r"^strike_p1$", r"^opt_m1_", r"^opt_p1_")),
    FeatureSetSpec(
        name="fo_iv_skew_only",
        include_regex=(
            r"^iv_",
            r".*_iv$",
            r"^iv_skew$",
            r"^ctx_is_high_vix_day$",
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_oi_pcr_momentum",
        include_regex=(
            r"^pcr_oi$",
            r"^ce_oi_total$",
            r"^pe_oi_total$",
            r"^ce_volume_total$",
            r"^pe_volume_total$",
            r"^ce_pe_oi_diff$",
            r"^ce_pe_volume_diff$",
            r"^fut_flow_oi_change_1m$",
            r"^fut_flow_oi_change_5m$",
            r"^fut_flow_oi_rel_20$",
            r"^fut_flow_oi_zscore_20$",
            r"^opt_flow_pcr_oi$",
            r"^opt_flow_atm_oi_change_1m$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_volume_diff$",
            r"^opt_flow_rel_volume_20$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_expiry_aware",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^regime_expiry_near$",
            r"^ret_",
            r"^ema_",
            r"^osc_rsi_14$",
            r"^osc_atr_",
            r"^vwap_distance$",
            r"^distance_from_day_",
            r"^dist_from_day_",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^dealer_proxy_",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_expiry_aware_v2",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_atr_high$",
            r"^regime_atr_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            r"^regime_expiry_near$",
            r"^ret_",
            r"^ema_",
            r"^osc_rsi_14$",
            r"^osc_atr_",
            r"^vwap_distance$",
            r"^distance_from_day_",
            r"^dist_from_day_",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^dealer_proxy_",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
]


def feature_set_specs_by_name() -> Dict[str, FeatureSetSpec]:
    return {spec.name: spec for spec in DEFAULT_FEATURE_SET_SPECS}


def feature_set_names() -> List[str]:
    return sorted(feature_set_specs_by_name())
