from __future__ import annotations

from typing import Dict, List

from ..contracts.types import FeatureSetSpec


DEFAULT_FEATURE_SET_SPECS: List[FeatureSetSpec] = [
    FeatureSetSpec(name="fo_full"),
    FeatureSetSpec(
        name="f5_core_atr",
        include_regex=(
            r"^f5_ret_",
            r"^f5_ema_",
            r"^f5_rsi_",
            r"^f5_atr_",
            r"^f5_bar_range_",
            r"^f5_vwap_distance$",
            r"^f5_dist_from_day_",
            r"^f5_basis",
            r"^f5_oi_",
            r"^f5_volume_",
            r"^f5_pcr_oi$",
            r"^f5_ce_pe_",
            r"^f5_bar_index$",
            r"^f5_minute_of_day$",
            r"^f5_day_of_week$",
            r"^f5_opening_range_",
        ),
    ),
    FeatureSetSpec(name="fo_no_opening_range", exclude_regex=(r"^opening_range_", r"^ctx_opening_range_")),
    FeatureSetSpec(
        name="fo_no_time_context",
        exclude_regex=(
            r"^minute_of_day$",
            r"^day_of_week$",
            r"^minute_index$",
            r"^time_minute_of_day$",
            r"^time_day_of_week$",
            r"^time_minute_index$",
        ),
    ),
    FeatureSetSpec(
        name="fo_no_oi_volume",
        exclude_regex=(
            r"^ce_oi_total$",
            r"^pe_oi_total$",
            r"^ce_volume_total$",
            r"^pe_volume_total$",
            r"^pcr_oi$",
            r"^ce_pe_oi_diff$",
            r"^ce_pe_volume_diff$",
            r"^atm_oi_change_1m$",
            r"^opt_.*_oi$",
            r"^opt_.*_volume$",
            r"^fut_flow_volume$",
            r"^fut_flow_oi$",
            r"^fut_flow_rel_volume_20$",
            r"^fut_flow_volume_accel_1m$",
            r"^fut_flow_oi_change_1m$",
            r"^fut_flow_oi_change_5m$",
            r"^fut_flow_oi_rel_20$",
            r"^fut_flow_oi_zscore_20$",
            r"^opt_flow_ce_oi_total$",
            r"^opt_flow_pe_oi_total$",
            r"^opt_flow_ce_volume_total$",
            r"^opt_flow_pe_volume_total$",
            r"^opt_flow_pcr_oi$",
            r"^opt_flow_atm_oi_change_1m$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_volume_diff$",
            r"^opt_flow_options_volume_total$",
            r"^opt_flow_rel_volume_20$",
        ),
    ),
    FeatureSetSpec(name="fo_no_otm_levels", exclude_regex=(r"^strike_m1$", r"^strike_p1$", r"^opt_m1_", r"^opt_p1_")),
    FeatureSetSpec(
        name="fo_iv_skew_only",
        include_regex=(
            r"^iv_",
            r".*_iv$",
            r"^iv_skew$",
            r"^ctx_is_high_vix_day$",
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_oi_pcr_momentum",
        include_regex=(
            r"^pcr_oi$",
            r"^ce_oi_total$",
            r"^pe_oi_total$",
            r"^ce_volume_total$",
            r"^pe_volume_total$",
            r"^ce_pe_oi_diff$",
            r"^ce_pe_volume_diff$",
            r"^fut_flow_oi_change_1m$",
            r"^fut_flow_oi_change_5m$",
            r"^fut_flow_oi_rel_20$",
            r"^fut_flow_oi_zscore_20$",
            r"^opt_flow_pcr_oi$",
            r"^opt_flow_atm_oi_change_1m$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_volume_diff$",
            r"^opt_flow_rel_volume_20$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_expiry_aware",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^regime_expiry_near$",
            r"^ret_",
            r"^ema_",
            r"^osc_rsi_14$",
            r"^osc_atr_",
            r"^vwap_distance$",
            r"^distance_from_day_",
            r"^dist_from_day_",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^dealer_proxy_",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_expiry_aware_v2",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_atr_high$",
            r"^regime_atr_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            r"^regime_expiry_near$",
            r"^ret_",
            r"^ema_",
            r"^osc_rsi_14$",
            r"^osc_atr_",
            r"^vwap_distance$",
            r"^distance_from_day_",
            r"^dist_from_day_",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^dealer_proxy_",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_expiry_aware_v3",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_atr_high$",
            r"^regime_atr_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            r"^regime_expiry_near$",
            r"^ret_",
            r"^ema_",
            r"^osc_rsi_14$",
            r"^osc_atr_",
            r"^vwap_distance$",
            r"^distance_from_day_",
            r"^dist_from_day_",
            r"^pcr$",
            r"^pcr_change_5m$",
            r"^pcr_change_15m$",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^ce_pe_oi_diff$",
            r"^atm_oi_ratio$",
            r"^near_atm_oi_ratio$",
            r"^atm_ce_oi$",
            r"^atm_pe_oi$",
            r"^atm_ce_iv$",
            r"^atm_pe_iv$",
            r"^iv_skew$",
            r"^iv_percentile$",
            r"^vix_current$",
            r"^vix_intraday_chg$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_midday_asymmetry",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_expiry_near$",
            r"^pcr$",
            r"^pcr_change_5m$",
            r"^pcr_change_15m$",
            r"^pcr_oi$",
            r"^ce_pe_oi_diff$",
            r"^ce_pe_volume_diff$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_volume_diff$",
            r"^atm_oi_ratio$",
            r"^near_atm_oi_ratio$",
            r"^atm_ce_oi$",
            r"^atm_pe_oi$",
            r"^dealer_proxy_oi_imbalance$",
            r"^dealer_proxy_oi_imbalance_change_5m$",
            r"^dealer_proxy_volume_imbalance$",
            r"^fut_flow_oi_change_1m$",
            r"^fut_flow_oi_change_5m$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
        ),
    ),
    FeatureSetSpec(
        name="fo_midday_expiry_interactions",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^regime_expiry_near$",
            r"^iv_skew$",
            r"^iv_percentile$",
            r"^atm_ce_iv$",
            r"^atm_pe_iv$",
            r"^vix_current$",
            r"^vix_intraday_chg$",
            r"^pcr$",
            r"^pcr_change_5m$",
            r"^pcr_change_15m$",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_atm_oi_change_1m$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    FeatureSetSpec(
        name="fo_midday_time_aware_plus_oi_iv",
        include_regex=(
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^ret_",
            r"^ema_",
            r"^osc_rsi_14$",
            r"^osc_atr_",
            r"^vwap_distance$",
            r"^distance_from_day_",
            r"^dist_from_day_",
            r"^pcr$",
            r"^pcr_change_5m$",
            r"^pcr_change_15m$",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^ce_pe_oi_diff$",
            r"^ce_pe_volume_diff$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_volume_diff$",
            r"^opt_flow_atm_oi_change_1m$",
            r"^atm_oi_ratio$",
            r"^near_atm_oi_ratio$",
            r"^atm_ce_oi$",
            r"^atm_pe_oi$",
            r"^atm_ce_iv$",
            r"^atm_pe_iv$",
            r"^iv_skew$",
            r"^iv_percentile$",
            r"^vix_current$",
            r"^vix_intraday_chg$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^time_day_of_week$",
        ),
    ),
    # S3: regime-aware direction feature set.
    # Drops confirmed regime-followers (pcr, iv_skew, atm_pe_iv, iv_percentile, dist_from_day_*).
    # Keeps weak anchors (ema slopes, atm_oi_ratio, vix_current).
    # Adds rolling oracle CE/PE win-rate features (computed by compute_rolling_oracle_stats in pipeline.py).
    FeatureSetSpec(
        name="fo_midday_direction_regime_v1",
        include_regex=(
            # Weak anchors: cross-window consistent CE/PE separation (small d, same sign)
            r"^ema_",
            r"^near_atm_oi_ratio$",
            r"^atm_oi_ratio$",
            r"^vix_current$",
            # Regime binary flags (computed in labeling/regime.py via attach_regime_features)
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_regime_expiry_near$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_vol_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            # Rolling oracle win-rate features (injected by compute_rolling_oracle_stats)
            r"^oracle_rolling_ce_win_rate_",
            r"^oracle_rolling_pe_win_rate_",
            r"^ce_pe_win_rate_diff_",
            # Velocity features (present in snapshots_ml_flat_v2 onwards; silently absent in v1)
            r"^vel_",
            r"^ctx_am_",
            r"^adx_14$",
            r"^vol_spike_ratio$",
            r"^ctx_gap_",
            # Intraday / expiry context
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^minutes_since_open$",
            r"^day_of_week$",
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
        ),
    ),
    # S3+: short-horizon regime variant.
    # Keeps the same weak anchors and regime flags as v1, but only the 5d oracle regime memory.
    # Goal: test whether the signal is more reactive and less diluted than the mixed 5d/10d pool.
    FeatureSetSpec(
        name="fo_midday_direction_regime_v2",
        include_regex=(
            r"^ema_",
            r"^near_atm_oi_ratio$",
            r"^atm_oi_ratio$",
            r"^vix_current$",
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_vol_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            r"^oracle_rolling_ce_win_rate_5d$",
            r"^oracle_rolling_pe_win_rate_5d$",
            r"^ce_pe_win_rate_diff_5d$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
        ),
    ),
    # Velocity feature set — for use with snapshots_ml_flat_v2 onwards.
    # Combines all 36 vel_/ctx_am_ velocity + morning-context features with the
    # proven weak anchors (EMA, ATR, VWAP, RSI) and expiry context.
    # Use for: Stage 1 entry gate, Stage 2 direction, Stage 3 recipe selection.
    FeatureSetSpec(
        name="fo_velocity_v1",
        include_regex=(
            r"^vel_",
            r"^ctx_am_",
            r"^adx_14$",
            r"^vol_spike_ratio$",
            r"^ctx_gap_",
            # Proven anchors from prior experiments
            r"^ema_",
            r"^price_vs_vwap$",
            r"^vwap_distance$",
            r"^rsi_14_",
            r"^osc_rsi_14$",
            r"^atr_14_",
            r"^osc_atr_",
            r"^near_atm_oi_ratio$",
            r"^atm_oi_ratio$",
            r"^vix_current$",
            # Regime flags
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_vol_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            # Expiry / time context
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^minutes_since_open$",
            r"^day_of_week$",
        ),
    ),
    # BMM (Big-Move Model) feature set — the velocity/structure backbone PLUS the new
    # compression / stored-energy / structure features computed by the shared
    # snapshot_app.core.compression_features module (present in stage views rebuilt with
    # add_compression_features; silently absent in older datasets). Raw values fed to the
    # model (NOT thresholded) per the BMM proposal. Level-invariant by construction.
    FeatureSetSpec(
        name="fo_bmm_v1",
        include_regex=(
            # --- NEW compression / stored-energy / structure (BMM) ---
            r"^bb_width_20$",
            r"^bb_width_chg_5$",
            r"^bb_width_5m$",
            r"^range_10$",
            r"^range_30$",
            r"^range_ratio_10_30$",
            r"^candle_overlap_10$",
            r"^ema_spread_9_21$",
            r"^ema_spread_21_50$",
            r"^ema_order$",
            r"^dist_from_ema21$",
            r"^position_in_day_range$",
            r"^compression_score$",
            # --- Existing structure / trend / vol backbone ---
            r"^ema_",
            r"^price_vs_vwap$",
            r"^vwap_distance$",
            r"^rsi_14_",
            r"^osc_rsi_14$",
            r"^atr_14_",
            r"^atr_ratio$",
            r"^atr_daily_percentile$",
            r"^osc_atr_",
            r"^realized_vol_30m$",
            r"^vol_ratio$",
            r"^or_width_pct$",
            r"^dist_from_day_high$",
            r"^dist_from_day_low$",
            r"^ret_",
            r"^fut_return_",
            r"^adx_14$",
            r"^vol_spike_ratio$",
            r"^mtf_aligned$",
            # --- Velocity / morning context (proven) ---
            r"^vel_",
            r"^ctx_am_",
            r"^ctx_gap_",
            # --- OI / PCR (de-correlated confirmers) ---
            r"^pcr$",
            r"^pcr_change_",
            r"^pcr_oi$",
            r"^near_atm_oi_ratio$",
            r"^atm_oi_ratio$",
            r"^near_atm_pcr$",
            r"^ce_pe_oi_diff$",
            r"^distance_to_max_pain_pct$",
            r"^atm_straddle_pct$",
            # --- Regime / VIX / expiry / session context ---
            r"^vix_current$",
            r"^vix_intraday_chg$",
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_vol_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            r"^ctx_dte_days$",
            r"^days_to_expiry$",
            r"^ctx_is_expiry_day$",
            r"^is_expiry_day$",
            r"^ctx_is_near_expiry$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^minutes_since_open$",
            r"^minutes_to_close$",
            r"^day_of_week$",
        ),
    ),
    # Per-side direction context — used by ce_win_v1 / pe_win_v1 dual-model labelers.
    # Combines all proven weak anchors + regime flags + velocity + IV structure + OI flow + oracle rolling.
    # Designed for: "is ATM CE (or PE) profitable today?" — full context, all sessions.
    FeatureSetSpec(
        name="fo_direction_entry_context_v1",
        include_regex=(
            # Price / momentum
            r"^ret_",
            r"^ema_",
            r"^vwap_distance$",
            r"^rsi_14_",
            r"^osc_rsi_14$",
            r"^adx_14$",
            r"^vol_spike_ratio$",
            # Velocity / morning context
            r"^vel_",
            r"^ctx_am_",
            r"^ctx_gap_",
            # Regime (strongest directional signal per R1S audit)
            r"^vix_current$",
            r"^vix_intraday_chg$",
            r"^ctx_is_high_vix_day$",
            r"^ctx_regime_",
            r"^regime_vol_",
            r"^regime_trend_",
            # OI / flow
            r"^pcr$",
            r"^pcr_change_5m$",
            r"^pcr_change_15m$",
            r"^pcr_oi$",
            r"^opt_flow_pcr_oi$",
            r"^ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_oi_diff$",
            r"^opt_flow_ce_pe_volume_diff$",
            r"^opt_flow_atm_oi_change_1m$",
            r"^atm_oi_ratio$",
            r"^near_atm_oi_ratio$",
            # IV structure
            r"^atm_ce_iv$",
            r"^atm_pe_iv$",
            r"^iv_skew$",
            r"^iv_percentile$",
            # Oracle rolling win-rate history
            r"^oracle_rolling_ce_win_rate_",
            r"^oracle_rolling_pe_win_rate_",
            r"^ce_pe_win_rate_diff_",
            # Time / expiry context
            r"^minutes_since_open$",
            r"^minute_of_day$",
            r"^time_minute_of_day$",
            r"^day_of_week$",
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
        ),
    ),
    # S3+: slower regime confirmation variant.
    # Uses only the 10d oracle regime features and drops minute-level context to reduce intraday overfit.
    # Goal: test whether a calmer, lower-variance directional signal generalizes better across windows.
    FeatureSetSpec(
        name="fo_midday_direction_regime_v3",
        include_regex=(
            r"^ema_",
            r"^near_atm_oi_ratio$",
            r"^atm_oi_ratio$",
            r"^vix_current$",
            r"^ctx_regime_atr_high$",
            r"^ctx_regime_atr_low$",
            r"^ctx_regime_trend_up$",
            r"^ctx_regime_trend_down$",
            r"^ctx_is_high_vix_day$",
            r"^regime_vol_high$",
            r"^regime_vol_low$",
            r"^regime_trend_up$",
            r"^regime_trend_down$",
            r"^oracle_rolling_ce_win_rate_10d$",
            r"^oracle_rolling_pe_win_rate_10d$",
            r"^ce_pe_win_rate_diff_10d$",
            r"^ctx_dte_days$",
            r"^ctx_is_expiry_day$",
            r"^ctx_is_near_expiry$",
        ),
    ),
    # Comprehensive entry feature set — the deliberate UNION of every engineered
    # feature group available in snapshots_ml_flat_v2/v3, built so the entry HPO
    # CANNOT collapse onto a 3-feature OI/volume subset (the fo_oi_pcr_momentum
    # failure documented in ENTRY_MODEL_FULLFEATURE_HANDOVER.md). It spans:
    #   - price momentum / EMA trend / oscillators / VWAP-distance / day-range
    #   - futures flow + full options flow (OI, volume, PCR, ATM OI change)
    #   - IV structure (skew, percentile, ATM CE/PE IV) when present in the view
    #   - VIX + daily macro regime + intraday regime flags + expiry context
    #   - velocity (vel_*, ctx_am_*, ctx_gap_*, adx, vol_spike) + oracle rolling
    # Level-invariant by construction: raw absolute price levels (px_*, vwap_fut,
    # absolute ATM strike) and the chain-row count are excluded so the model does
    # not learn the 2022->2026 index drift. Regexes for columns absent from a
    # given dataset are silently dropped by the resolver.
    FeatureSetSpec(
        name="fo_comprehensive",
        include_regex=(
            # Price momentum / trend / volatility
            r"^ret_",
            r"^ema_",
            r"^osc_",
            r"^rsi_14_",
            r"^atr_14_",
            r"^adx_14$",
            r"^vol_spike_ratio$",
            r"^price_vs_vwap$",
            r"^vwap_distance$",
            r"^dist_",
            r"^distance_from_day_",
            # Futures flow
            r"^fut_flow_",
            # Options flow / OI / PCR
            r"^opt_flow_",
            r"^pcr$",
            r"^pcr_oi$",
            r"^pcr_change_5m$",
            r"^pcr_change_15m$",
            r"^atm_oi_ratio$",
            r"^near_atm_oi_ratio$",
            r"^ce_oi_total$",
            r"^pe_oi_total$",
            r"^ce_volume_total$",
            r"^pe_volume_total$",
            r"^ce_pe_oi_diff$",
            r"^ce_pe_volume_diff$",
            r"^atm_ce_oi$",
            r"^atm_pe_oi$",
            r"^dealer_proxy_",
            # IV structure (present in enriched views; silently absent otherwise)
            r"^iv_",
            r".*_iv$",
            r"^iv_skew$",
            r"^iv_percentile$",
            r"^vix_current$",
            r"^vix_intraday_chg$",
            # Daily macro regime + intraday regime flags
            r"^regime_",
            r"^ctx_",
            # Velocity / morning context
            r"^vel_",
            r"^ctx_am_",
            r"^ctx_gap_",
            # Oracle rolling win-rate memory
            r"^oracle_rolling_ce_win_rate_",
            r"^oracle_rolling_pe_win_rate_",
            r"^ce_pe_win_rate_diff_",
            # Time / session context
            r"^time_",
            r"^minute_of_day$",
            r"^minute_index$",
            r"^minutes_since_open$",
            r"^day_of_week$",
        ),
        exclude_regex=(
            # Raw absolute price levels — non-stationary across index drift
            r"^px_",
            r"^vwap_fut$",
            # Absolute strike level + raw chain-row count (pure noise / level)
            r"^opt_flow_atm_strike$",
            r"^opt_flow_rows$",
        ),
    ),
]


def feature_set_specs_by_name() -> Dict[str, FeatureSetSpec]:
    return {spec.name: spec for spec in DEFAULT_FEATURE_SET_SPECS}


def feature_set_names() -> List[str]:
    return sorted(feature_set_specs_by_name())
