from __future__ import annotations

from typing import List, Tuple

import numpy as np
import pandas as pd

from ..catalog.feature_profiles import apply_feature_profile


IDENTITY_COLUMNS: Tuple[str, ...] = (
    "timestamp",
    "trade_date",
    "fut_symbol",
    "expiry_code",
    "source_day",
    "ce_symbol",
    "pe_symbol",
)

LABEL_COLUMNS: Tuple[str, ...] = (
    "entry_label",
    "direction_label",
    "direction_up",
    "recipe_label",
    "chosen_direction_up",
    "best_net_return_after_cost",
    "best_ce_net_return_after_cost",
    "best_pe_net_return_after_cost",
    "best_available_net_return_after_cost",
    "label_horizon_minutes",
    "label_return_threshold",
    "ce_entry_price",
    "ce_exit_price",
    "ce_realized_return",
    "ce_forward_return",
    "ce_mfe",
    "ce_mae",
    "ce_label_valid",
    "ce_label",
    "pe_entry_price",
    "pe_exit_price",
    "pe_realized_return",
    "pe_forward_return",
    "pe_mfe",
    "pe_mae",
    "pe_label_valid",
    "pe_label",
    "pe_tp_hit",
    "pe_sl_hit",
    "pe_first_hit",
    "pe_first_hit_offset_min",
    "pe_path_exit_reason",
    "pe_tp_price",
    "pe_sl_price",
    "pe_time_stop_exit",
    "pe_hold_extension_eligible",
    "pe_triple_barrier_state",
    "pe_barrier_upper_return",
    "pe_barrier_lower_return",
    "ce_tp_hit",
    "ce_sl_hit",
    "ce_first_hit",
    "ce_first_hit_offset_min",
    "ce_path_exit_reason",
    "ce_tp_price",
    "ce_sl_price",
    "ce_time_stop_exit",
    "ce_hold_extension_eligible",
    "ce_triple_barrier_state",
    "ce_barrier_upper_return",
    "ce_barrier_lower_return",
    "ce_path_target_valid",
    "pe_path_target_valid",
    "long_entry_price",
    "long_exit_price",
    "long_realized_return",
    "long_forward_return",
    "long_mfe",
    "long_mae",
    "long_label_valid",
    "long_label",
    "long_tp_hit",
    "long_sl_hit",
    "long_first_hit",
    "long_first_hit_offset_min",
    "long_path_exit_reason",
    "long_tp_price",
    "long_sl_price",
    "long_time_stop_exit",
    "long_hold_extension_eligible",
    "long_triple_barrier_state",
    "long_barrier_upper_return",
    "long_barrier_lower_return",
    "long_path_target_valid",
    "short_entry_price",
    "short_exit_price",
    "short_realized_return",
    "short_forward_return",
    "short_mfe",
    "short_mae",
    "short_label_valid",
    "short_label",
    "short_tp_hit",
    "short_sl_hit",
    "short_first_hit",
    "short_first_hit_offset_min",
    "short_path_exit_reason",
    "short_tp_price",
    "short_sl_price",
    "short_time_stop_exit",
    "short_hold_extension_eligible",
    "short_triple_barrier_state",
    "short_barrier_upper_return",
    "short_barrier_lower_return",
    "short_path_target_valid",
    "move_label_valid",
    "move_label",
    "move_path_exit_reason",
    "move_first_hit_side",
    "move_event_end_ts",
    "move_barrier_upper_return",
    "move_barrier_lower_return",
    "best_side_label",
)


def select_feature_columns(df: pd.DataFrame, feature_profile: str = "all") -> List[str]:
    excluded = set(IDENTITY_COLUMNS) | set(LABEL_COLUMNS)
    numeric_cols = list(df.select_dtypes(include=[np.number]).columns)
    selected = [col for col in numeric_cols if col not in excluded]
    return apply_feature_profile(selected, feature_profile=feature_profile)
